### PR TITLE
Feature/scripting - Update transpiler to use moo

### PR DESCRIPTION
**Pull request by jsm174**
This PR updates the transpiler to use the moo lexer. It simplifies the grammar, speeds up parsing, and helps reduce ambiguity.

### CODE REVIEW

**Comment by freezy** [comment]
```vbs

Dim EnableBallControl
EnableBallControl = false 'Change to true to enable manual ball control (or press C in-game) via the arrow keys and B (boost movement) keys
```
This hangs indefinitely

**Comment by freezy** [comment]
```vbs
If keycode = 46 Then
	If EnableBallControl = 1 Then
		EnableBallControl = 0
	Else
		EnableBallControl = 1
	End If
End If
```

Results in *Parser returned no results*.

**Comment by freezy** [comment]
```vbs
Dim RStep, Lstep

Sub RightSlingShot_Slingshot
    RSling.Visible = 0
    RSling1.Visible = 1
    sling1.rotx = 20
    RStep = 0
    RightSlingShot.TimerEnabled = 1
	gi1.State = 0:Gi2.State = 0
End Sub
```
Results in *Parser returned no results*.

**Comment by jsm174** [comment]
>  but for comments it looks weird.

I thought in the early stage of testing it would be good to include comments. As far as I can tell there is no way to have comments, other than to make an `EmptyStatements`. `EmptyStatements` seem to render with `;`

**Comment by freezy** [comment]
```vbs
Dim test 
```
(with a trailing space)

Results in:

```
Error: Syntax error at line 1 col 9:

  Dim test
          ^
Unexpected ws token: " ". Instead, I was expecting to see one of the following:

A comma token based on:
    DimOtherVars →  ● %comma _ DimVarName
    DimVarList$ebnf$1 → DimVarList$ebnf$1 ● DimOtherVars
    DimVarList → DimVarName ● DimVarList$ebnf$1
    DimDecl → %kw_dim __ ● DimVarList NL
    BlockStmt → _ ● DimDecl
    GlobalStmt → _ ● BlockStmt
    Program$ebnf$2 → Program$ebnf$2 ● GlobalStmt
    Program → Program$ebnf$1 ● Program$ebnf$2
A nl token based on:
    NL →  ● %nl
    DimDecl → %kw_dim __ DimVarList ● NL
    BlockStmt → _ ● DimDecl
    GlobalStmt → _ ● BlockStmt
    Program$ebnf$2 → Program$ebnf$2 ● GlobalStmt
    Program → Program$ebnf$1 ● Program$ebnf$2
```

**Pull request merged**
